# QA environment properties
baseUrl=https://yuva-beta.mybharats.in/
apiEndpoint=https://mybharat.gov.in/
browser=firefox
environment=https://mybharat.gov.in/
url=https://yuva-beta.mybharats.in/
dummyEmail=https://yopmail.com/