# Global properties
url=https://yuva-beta.mybharats.in/
timeout=30
locale=en_US
browser=headless
#  environment=https://devyuva.mybharats.in/
# environment=https://yuva-beta.mybharats.in/
environment=https://mybharat.gov.in/

dummyEmail=https://yopmail.com/
password=25@March